# Generated by Django 5.2.13 on 2026-04-09 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Senior Faculty Behavioral Set 1'", max_length=255)),
                ('category', models.CharField(choices=[('BEHAVIORAL', 'Behavioral'), ('APTITUDE', 'Aptitude'), ('TECHNICAL', 'Technical'), ('PEDAGOGY', 'Teaching/Pedagogy')], default='BEHAVIORAL', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('priority', models.IntegerField(default=1, help_text='1 is highest priority. Questions sort by this number.')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ARAS.questionset')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('question_sets', models.ManyToManyField(blank=True, to='ARAS.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('status', models.CharField(choices=[('AWAITING_UPLOAD', 'Awaiting Resume Upload'), ('IN_PROGRESS', 'Interview In Progress'), ('COMPLETED', 'Interview Completed')], default='AWAITING_UPLOAD', max_length=20)),
                ('hybrid_questions_payload', models.JSONField(blank=True, null=True)),
                ('answers_payload', models.JSONField(blank=True, null=True)),
                ('ai_overall_score', models.IntegerField(blank=True, help_text='Score out of 100', null=True)),
                ('skills_gap_analysis', models.TextField(blank=True, help_text='What the candidate lacks for the role', null=True)),
                ('behavioral_summary', models.TextField(blank=True, help_text="e.g., 'Handles pressure well, great pedagogy'", null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ARAS.jobrole')),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='idx_users_email'), models.Index(fields=['uuid'], name='idx_users_uuid')],
            },
        ),
    ]
