# Generated by Django 5.2.13 on 2026-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARAS', '0002_remove_user_ai_overall_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_overall_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='behavioral_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills_gap_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
